language: python
python:
  - "3.6"

dist: trusty

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database rootdb;' -U postres
  
script:
  - pytest --cov=. tests/

after_success:
  - coveralls
