language: python
python:
  - "2.7"


dist: trusty

cache: pip

install:
  - pip install -r requirements.txt

script:
  - pytest tests
  - coverage run --source='app/' app.py test
  - coverage report

after_success:
  - coveralls
