language: python
python:
  - "3.6"

dist: trusty

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database mydiarydb;' -U postgres
  
script:
  - pytest --cov

after_success:
  - coveralls
